/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author zezos
 */
public class LeaderBoard extends javax.swing.JFrame {

    /**
     * Creates new form LeaderBoard
     */
    public LeaderBoard() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DashBoard = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PlayerName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PlaceBackground = new javax.swing.JLabel();
        ThirdPlaceBackground = new javax.swing.JLabel();
        SconedPlaceBackground = new javax.swing.JLabel();
        FirstPlaceBackground = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LeaderBoard_Title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BackButtonL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 800));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setMaximumSize(new java.awt.Dimension(360, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashBoard.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        DashBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashBoard.setHorizontalScrollBar(null);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/PP_backgorund.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/PP_backgorund.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        PlayerName.setFont(new java.awt.Font("Silkscreen", 0, 25)); // NOI18N
        PlayerName.setText("1. Player 1");
        jPanel3.add(PlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/PP_backgorund.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/PP_backgorund.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        PlaceBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/PP_backgorund.png"))); // NOI18N
        jPanel3.add(PlaceBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        ThirdPlaceBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/P3_backgorund.png"))); // NOI18N
        jPanel3.add(ThirdPlaceBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        SconedPlaceBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/P2_backgorund.png"))); // NOI18N
        jPanel3.add(SconedPlaceBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        FirstPlaceBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/P1_backgorund.png"))); // NOI18N
        jPanel3.add(FirstPlaceBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/PP_backgorund.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/PP_backgorund.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        DashBoard.setViewportView(jPanel3);

        jPanel1.add(DashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 310));
        DashBoard.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));

        LeaderBoard_Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/LeaderBoard.png"))); // NOI18N
        jPanel1.add(LeaderBoard_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 143, -1, -1));

        jPanel2.setBackground(new java.awt.Color(196, 207, 161));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 31, 31)));
        jPanel2.setMaximumSize(new java.awt.Dimension(360, 90));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 90));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 90));

        BackButtonL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Back.png"))); // NOI18N
        BackButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonLActionPerformed(evt);
            }
        });
        BackButtonL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackButtonLKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BackButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackButtonL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonLActionPerformed
        try {
            System.out.println("Back");
            GameField GF = new GameField();
            GF.show();
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LeaderBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BackButtonLActionPerformed

    private void BackButtonLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackButtonLKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {

            try {
                GameField GF = new GameField();
                GF.show();
                this.dispose();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LeaderBoard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BackButtonLKeyPressed

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButtonL;
    private javax.swing.JScrollPane DashBoard;
    private javax.swing.JLabel FirstPlaceBackground;
    private javax.swing.JLabel LeaderBoard_Title;
    private javax.swing.JLabel PlaceBackground;
    private javax.swing.JLabel PlayerName;
    private javax.swing.JLabel SconedPlaceBackground;
    private javax.swing.JLabel ThirdPlaceBackground;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
