/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author zezos
 */
public class Main_page extends javax.swing.JFrame {

    /**
     * Creates new form Main_page
     */
    public Main_page() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Main = new javax.swing.JLabel();
        PlayButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        ToggleBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 800));

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setMaximumSize(new java.awt.Dimension(360, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Main.png"))); // NOI18N
        Main.setAlignmentY(0.0F);
        jPanel1.add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 231, -1, -1));

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Play.png"))); // NOI18N
        PlayButton.setBorder(null);
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        PlayButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PlayButtonKeyPressed(evt);
            }
        });
        jPanel1.add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 503, 120, 40));

        AboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ABOUT.png"))); // NOI18N
        AboutButton.setBorder(null);
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });
        AboutButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AboutButtonKeyPressed(evt);
            }
        });
        jPanel1.add(AboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 503, 110, 30));

        ToggleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Options_Back.png"))); // NOI18N
        ToggleBackground.setToolTipText("");
        jPanel1.add(ToggleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 478, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AboutButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                About ab = new About(this);
                ab.show();
            } catch (Exception e) {

            }
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_AboutButtonKeyPressed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        try {
            About ab = new About(this);
            ab.show();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_AboutButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        UserPanel UP = new UserPanel(this);
        UP.show();
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void PlayButtonKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_PlayButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                UserPanel UP = new UserPanel(this);
                UP.show();
            } catch (Exception e) {

            }
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }// GEN-LAST:event_PlayButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         * 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JLabel Main;
    private javax.swing.JButton PlayButton;
    private javax.swing.JLabel ToggleBackground;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
