/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;


import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author zezos
 */
public class Win extends javax.swing.JFrame {

    /**
     * Creates new form WIn
     */
    public Win(JFrame source) {
        initComponents();
        this.source = source;
       Point pt = source.getLocation() ;
        setLocation(pt.x+3, pt.y + source.getHeight()/3);

        this.Win.setLocation(76, 90);
        this.Win2.setLocation(80, 31);
        this.Win3.setLocation(80, 140);
        this.Win.setFont(new java.awt.Font("Silkscreen", 0, 18));
        this.Win2.setFont(new java.awt.Font("Silkscreen", 0, 24));
        this.Win3.setFont(new java.awt.Font("Silkscreen", 0, 24));
        this.show();
        try {
            for (int i = 0; i <= 360; i += 5) {
                Thread.sleep(60);
                if (i <= 180) {
                    this.Win2.setLocation(140 + i, 31);
                    this.Win3.setLocation(100 - i, 140);

                } else {
                    this.Win2.setLocation(i - 180, 31);
                    this.Win3.setLocation(360 - (i - 180), 140);

                }
            }
            Thread.sleep(100);
            this.Win2.setText("");
            this.Win3.setText("");

        } catch (Exception e) {
        } finally {
            this.Win2.setLocation(90, 80);
            this.Win.setFont(new java.awt.Font("Silkscreen", 0, 20));
            //edit ya MR shaaheen :)
            this.Win.setText("Press AnY KEY to play again ESC to close");
            Thread.currentThread().stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Win1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Win = new javax.swing.JLabel();
        Win2 = new javax.swing.JLabel();
        Win3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        Win1.setFont(new java.awt.Font("Silkscreen", 0, 18)); // NOI18N
        Win1.setForeground(new java.awt.Color(196, 207, 161));
        Win1.setText("We got a winner");
        Win1.setPreferredSize(new java.awt.Dimension(209, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 200));
        setMinimumSize(new java.awt.Dimension(360, 200));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setForeground(new java.awt.Color(31, 31, 31));
        jPanel1.setMaximumSize(new java.awt.Dimension(360, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(360, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Win.setFont(new java.awt.Font("Silkscreen", 0, 18)); // NOI18N
        Win.setForeground(new java.awt.Color(196, 207, 161));
        Win.setText("   We got a winner");
        Win.setAlignmentY(0.0F);
        Win.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Win.setPreferredSize(new java.awt.Dimension(209, 20));
        Win.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(Win, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 240, 19));

        Win2.setFont(new java.awt.Font("Silkscreen", 0, 24)); // NOI18N
        Win2.setForeground(new java.awt.Color(196, 207, 161));
        Win2.setText("winner");
        Win2.setPreferredSize(new java.awt.Dimension(209, 20));
        jPanel1.add(Win2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 160, 100, 25));

        Win3.setFont(new java.awt.Font("Silkscreen", 0, 24)); // NOI18N
        Win3.setForeground(new java.awt.Color(196, 207, 161));
        Win3.setText("winner");
        Win3.setPreferredSize(new java.awt.Dimension(209, 20));
        jPanel1.add(Win3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 100, 25));

        jButton1.setBackground(new java.awt.Color(31, 31, 31));
        jButton1.setForeground(new java.awt.Color(31, 31, 31));
        jButton1.setBorder(null);
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ESCAPE) {
            Main_page mp = new Main_page();
            dispose();
            source.dispose();
            mp.setVisible(true);
        } else {
            try {
                GameField Gf = new GameField();
                dispose();
                source.dispose();
                Thread.sleep(20);
                Gf.setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Win(source).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Win;
    public javax.swing.JLabel Win1;
    public javax.swing.JLabel Win2;
    public javax.swing.JLabel Win3;
    private javax.swing.JButton jButton1;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private static JFrame source ;
}
